### ISSUE TITLE
building with llvm-9.0.0

### ISSUE THREAD

**Issue by nburow2** [kevinkoo001/CCR#4]
I'm interested in building with llvm-9.0.0.  I updated the LLVM directory in your buildscript, but then am getting many errors when it tries to link libclang_shared.so .  The errors all refer to google::protobuf::* .  did I miss a step?

**Comment by kevinkoo001** [comment]
Thanks for your interest in CCR. Check out the library is located in the location. Make sure to use `ld.bfd` instead of `ld.gold` when you build llvm-9.0.0.  And try `sudo ldconfig` that all shared libraries for CCR could be deployed.

**Comment by nburow2** [comment]
Hi, thanks for your response.  Reverting to `ld.bfd` made things worse, as the shuffleInfo functions were no longer found.  I've previously built CCR with llvm-3.9.0 on the same system.  Could that be interfering? If so, what's the uninstall procedure? 

In fact, given that CCR with llvm-3.9 worked, I'm reasonably confident that the protobuf library is there and that `sudo ldconfig` worked.  `build.sh` edits some of the files cmake generates -- is that the same set for llvm-9.0 as for llvm-3.9?

**Comment by kevinkoo001** [comment]
Well, I think you do not need a uninstall process. Just remove the CCR link (i.e., `/usr/local/bin/ccr`), and revert the default linker to the original one (i.e., `/usr/bin/ld.bfd`). And you can generate CCR with llvm-9 with updating `LLVM_DIR` in `build.sh`. Or following the step E in the build script would be sufficient as you already have done other steps.

**Comment by nburow2** [comment]
I got it to build on a clean VM.
