### ISSUE TITLE
How to build project with ccr?

### ISSUE THREAD

**Issue by tkyzp** [kevinkoo001/CCR#7]
Recently, I need to test your tools. But I don't know how to build C/C++ projects which originally compiled with makefile. Do you have some docs about that? Or can I get technical support?

**Comment by kevinkoo001** [comment]
Thank you for your interest in CCR. Well, I think the best way to give it a try is using Docker, which does not require a build process. As CCR offers a simple script to start with, it should not be hard. Please check out the `Build with Docker` instruction.
