### ISSUE TITLE
Build failing to enable randomizing

### ISSUE THREAD

**Issue by RSAkidinUSA** [kevinkoo001/CCR#8]
I have been trying to build [ffmpeg](https://ffmpeg.org/about.html) [git repo](https://git.ffmpeg.org/ffmpeg.git) with some issues. I first modified their makefile to replace all calls to $(LD) with $(CC) since it appears that building intermediary .o files with ccr and then linking with the modified loader causes those binaries to fail. e.g.
```
echo "int main() { return 0; }" > test.c;
ccr -c -o test.o test.c;
/home/<user>/CCR/binutils-2.27/gold/ld-new -o a.out test.o
./a.out
```
will cause a seg-fault.

I've modified their makefile to link using ccr instead of ld, but now I get the following errors when trying to randomize:
`WARNING:root:   [.text] Fails to discover the reference BBL (Fixup#9)`
and
`WARNING:root:   [.data] No legitimate RefBBL (Fixup#9776)`

I've attached the modified [Makefile](https://github.com/kevinkoo001/CCR/files/5285137/Makefile.txt), and the environment can be setup by running 
```
CCR=/usr/local/bin/ccr
CCRPP=/usr/local/bin/ccr++
./configure --cc=$CCR --cxx=$CCRPP
```

Any help would be greatly appreciated!

**Comment by kevinkoo001** [comment]
Can you let me know your environment (OS) when you build/run ccr? I recommend you to use Docker for the test purpose in the beginning.  I have not tried ffmpeg but it contains a large source code base, so possibly an unknown case might be encountered that cannot be handled with the current version. I remember those errors happen when a fixup that must be updated after transformation does not match any referencing basic block.

**Comment by RSAkidinUSA** [comment]
It's on Ubuntu 18.04 environment. I've successfully built a full suite of other simpler benchmarks with CCR in the environment and been able to randomize them, however this program had a lot of intermediary files that may be the source of errors.

**Comment by kevinkoo001** [comment]
Lately, Chengbin et al. extended CCR concept to gcc backend as well. I guess their implementation (i.e., linker) handles more corner cases. Check out here: https://github.com/junxzm1990/x86-sok/
